export const content = {
  en: {
    // Header
    login: 'Login',
    register: 'Create Account',
    languageToggle: 'العربية',
    // Sidebar
    navHome: 'Home',
    navActivities: 'Activities',
    navGallery: 'Gallery',
    navContact: 'Contact Us',
    navDashboard: 'Dashboard',
    // Homepage
    statsTitle: 'Our Community in Numbers',
    members: 'Members',
    activities: 'Activities',
    events: 'Events',
    talents: 'Talents',
    activitiesTitle: 'Latest Activities',
    free: 'Free',
    paid: 'Paid',
    viewAll: 'View All',
    tripsTitle: 'Upcoming Trips',
    eventsTitle: 'Our Grand Annual Event',
    eventsDescription:
      'Join us for our biggest event of the year, full of surprises, shows, and fun activities for the whole family. Register now to secure your spot!',
    eventsButton: 'Learn More & Register',
    talentsTitle: 'Discover New Talents',
    talentsDescription:
      'We are proud to showcase the amazing talents within our community. From artists to athletes, discover the stars of tomorrow.',
    talentsButton: 'Explore Talents',
    // Login Page
    loginTitle: 'Welcome Back!',
    loginSubtitle: 'Enter your credentials to access your account',
    emailLabel: 'Email',
    passwordLabel: 'Password',
    loginButton: 'Login',
    loginNoAccount: "Don't have an account?",
    // Register Page
    registerTitle: 'Create a New Account',
    registerSubtitle: 'Join our community and start participating!',
    nameLabel: 'Full Name',
    confirmPasswordLabel: 'Confirm Password',
    registerButton: 'Create Account',
    registerHasAccount: 'Already have an account?',
    // Dashboard
    dashboardTitle: 'Content Management',
    manageActivities: 'Activities',
    manageTrips: 'Trips',
    manageEvents: 'Events',
    manageTalents: 'Talents',
    manageGallery: 'Gallery',
    manageSlider: 'Slider',
    addActivity: 'Add Activity',
    activityTitleLabel: 'Activity Title',
    activityDescriptionLabel: 'Description',
    suggestTags: 'Suggest Tags',
    suggestedTags: 'Suggested Tags',
    submit: 'Submit',
    // Subscription Form
    subscribeButton: 'Subscribe',
    subscriptionSuccessTitle: 'Success!',
    subscriptionSuccessMessage: 'You have been subscribed to the activity.',
    studentNameLabel: 'Student Name',
    classLabel: 'Class',
    phoneLabel: 'Phone Number',
  },
  ar: {
    // Header
    login: 'تسجيل الدخول',
    register: 'إنشاء حساب',
    languageToggle: 'English',
    // Sidebar
    navHome: 'الرئيسية',
    navActivities: 'الأنشطة',
    navGallery: 'معرض الصور',
    navContact: 'اتصل بنا',
    navDashboard: 'لوحة التحكم',
    // Homepage
    statsTitle: 'مجتمعنا في أرقام',
    members: 'عضو',
    activities: 'نشاط',
    events: 'فعالية',
    talents: 'موهبة',
    activitiesTitle: 'أحدث الأنشطة',
    free: 'مجاني',
    paid: 'مدفوع',
    viewAll: 'عرض الكل',
    tripsTitle: 'الرحلات القادمة',
    eventsTitle: 'فعاليتنا السنوية الكبرى',
    eventsDescription:
      'انضم إلينا في أكبر حدث لنا هذا العام، المليء بالمفاجآت والعروض والأنشطة الممتعة لجميع أفراد العائلة. سجل الآن لتضمن مكانك!',
    eventsButton: 'اعرف المزيد وسجل',
    talentsTitle: 'اكتشف مواهب جديدة',
    talentsDescription:
      'نفخر بعرض المواهب المذهلة في مجتمعنا. من الفنانين إلى الرياضيين، اكتشف نجوم الغد.',
    talentsButton: 'استكشف المواهب',
    // Login Page
    loginTitle: 'مرحباً بعودتك!',
    loginSubtitle: 'أدخل بياناتك للوصول إلى حسابك',
    emailLabel: 'البريد الإلكتروني',
    passwordLabel: 'كلمة المرور',
    loginButton: 'تسجيل الدخول',
    loginNoAccount: 'ليس لديك حساب؟',
    // Register Page
    registerTitle: 'إنشاء حساب جديد',
    registerSubtitle: 'انضم إلى مجتمعنا وابدأ في المشاركة!',
    nameLabel: 'الاسم الكامل',
    confirmPasswordLabel: 'تأكيد كلمة المرور',
    registerButton: 'إنشاء حساب',
    registerHasAccount: 'لديك حساب بالفعل؟',
    // Dashboard
    dashboardTitle: 'إدارة المحتوى',
    manageActivities: 'الأنشطة',
    manageTrips: 'الرحلات',
    manageEvents: 'الفعاليات',
    manageTalents: 'الموهوبين',
    manageGallery: 'المعرض',
    manageSlider: 'السلايدر',
    addActivity: 'إضافة نشاط',
    activityTitleLabel: 'عنوان النشاط',
    activityDescriptionLabel: 'الوصف',
    suggestTags: 'اقترح وسوم',
    suggestedTags: 'الوسوم المقترحة',
    submit: 'إرسال',
    // Subscription Form
    subscribeButton: 'اشتراك',
    subscriptionSuccessTitle: 'نجاح!',
    subscriptionSuccessMessage: 'لقد تم تسجيل اشتراكك في النشاط بنجاح.',
    studentNameLabel: 'اسم الطالب',
    classLabel: 'الفصل',
    phoneLabel: 'رقم الهاتف',
  },
};
